### ISSUE TITLE
Python package install issue

### ISSUE THREAD

**Issue by KimYC1223** [KimYC1223/3D-Body-Estimation#4]
> Hello, I found your project very interesting.
> Unfortunatally during the installation of the needed packages some of the versions you > > report are too old and are automatically unistalled and substituted (i.e. numpy during the installation of scipy and traits during the installation of mayavi).
> At the end running the demo program I receive errors.
> Can you either update your list of programs that need to be installed or specify the exact > version also for mayavi and scipy.
> Thank you very much

_Originally posted by @suptec19 in https://github.com/KimYC1223/3D-Body-Estimation/issues/3#issuecomment-953164264_

**Comment by KimYC1223** [comment]
# Python package install issue

### Reference

- #3
by @suptec19

---

### Suggestion

this project referenced to [3D Human Body Reshaping with Anthropometric Modeling](https://github.com/1900zyh/3D-Human-Body-Shape).

So, I found version infomation in original [git repo](https://github.com/1900zyh/3D-Human-Body-Shape/blob/master/requirements.txt).

- **scipy==1.2.1**
- **mayavi==4.7.1**

Try installing with the version information above.

---

It's been a long time since I've been working on this project,

so I need to reinstall my environments to improve this github repo.

And... unfortunately, I can't confirm that version is the correct

because I'm working on other project right now.

Give it a try, and if it still doesn't work, please contact me again. 👍

Thank you !!

**Comment by suptec19** [comment]
Dear Kim,
thank you for your support, but even with all the correct versions in a virtual environment, finally I get the following error:
```
Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    from maya_widget import MayaviQWidget, myAction, IndexedQSlider
  File "C:\Users\Andrea\Desktop\test\3D\3D-Human-Body-Shape-original\src\maya_widget.py", line 12, in <module>
    from reshaper import Reshaper
  File "C:\Users\Andrea\Desktop\test\3D\3D-Human-Body-Shape-original\src\reshaper.py", line 5, in <module>
    from fancyimpute import IterativeImputer as MICE
  File "C:\Users\Andrea\Desktop\test\3D\3D-Human-Body-Shape-original\src\test\env\lib\site-packages\fancyimpute\__init__.py", line 7, in <module>
    from .matrix_factorization import MatrixFactorization
  File "C:\Users\Andrea\Desktop\test\3D\3D-Human-Body-Shape-original\src\test\env\lib\site-packages\fancyimpute\matrix_factorization.py", line 24, in <module>
    from .keras_models import KerasMatrixFactorizer
  File "C:\Users\Andrea\Desktop\test\3D\3D-Human-Body-Shape-original\src\test\env\lib\site-packages\fancyimpute\keras_models.py", line 17, in <module>
    from keras.engine import Layer
ImportError: cannot import name 'Layer' from 'keras.engine' (C:\Users\Andrea\Desktop\test\3D\3D-Human-Body-Shape-original\src\test\env\lib\site-packages\keras\engine\__init__.py)
```

**Comment by suptec19** [comment]
these are the installed packages:
`pip list`

```
Package                 Version
----------------------- -----------
absl-py                 0.15.0
apptools                5.1.0
astunparse              1.6.3
cached-property         1.5.2
cachetools              4.2.4
certifi                 2021.10.8
charset-normalizer      2.0.7
clang                   5.0
configobj               5.0.6
cvxpy                   1.0.21
Cython                  0.29.7
dill                    0.3.4
ecos                    2.0.7.post1
envisage                6.0.1
et-xmlfile              1.1.0
fancyimpute             0.3.2
fastcache               1.1.0
flatbuffers             1.12
future                  0.18.2
gast                    0.4.0
google-auth             2.3.2
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.41.1
h5py                    3.1.0
idna                    3.3
importlib-metadata      4.8.1
importlib-resources     5.3.0
jdcal                   1.4.1
joblib                  1.1.0
keras                   2.6.0
Keras-Preprocessing     1.1.2
knnimpute               0.1.0
Markdown                3.3.4
mayavi                  4.7.1
multiprocess            0.70.12.2
np-utils                0.5.12.1
numpy                   1.19.5
oauthlib                3.1.1
openpyxl                2.6.2
opt-einsum              3.3.0
osqp                    0.6.2.post0
pip                     21.3.1
protobuf                3.19.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyface                  7.3.0
Pygments                2.10.0
PyOpenGL                3.1.0
PyQt5                   5.10.1
qdldl                   0.1.5.post0
requests                2.26.0
requests-oauthlib       1.3.0
rsa                     4.7.2
scikit-learn            0.21.3
scipy                   1.2.1
scs                     2.1.4
setuptools              56.0.0
sip                     4.19.8
six                     1.15.0
tensorboard             2.7.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.6.0
tensorflow-estimator    2.6.0
termcolor               1.1.0
threadpoolctl           3.0.0
traits                  6.3.1
traitsui                7.2.1
typing-extensions       3.7.4.3
urllib3                 1.26.7
vtk                     8.1.2
Werkzeug                2.0.2
wheel                   0.36.2
wrapt                   1.12.1
zipp                    3.6.0
```

**Comment by KimYC1223** [comment]
Thank you for your report

It's so sad that it's not easy to solve 😢

I'll try setting the environment again myself,

and get back to you about the version. 

I'll try it myself this weekend!
